name: Cache Firestore Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  cache-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Fetch and Write Cache
      run: node index.js
      env:
        TRACKSTORE_SERVICE_ACCOUNT_KEY: ${{ secrets.TRACKSTORE_SERVICE_ACCOUNT_KEY }}

    - name: Deploy Cache to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/
